import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { Providers } from "./provider";
import React from "react";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Next.js Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>

      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            inter.className,
            "bg-white dark:bg-gray-900 dark:text-white"
          )}>
          <div className="md:mx-5 mx-1">
            <Providers>{children}</Providers>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
